In [20]:
import numpy as np

## Numpy array

In [21]:
myList = [20,30,40]

In [22]:
np.array(myList)

array([20, 30, 40])

In [23]:
matrixList = [[10,20,30],[40,50,60],[70,80,90]]

In [24]:
np.array(matrixList)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## Arange

In [25]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## Zeros

In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

## Ones

In [31]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Linspace

In [33]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

## Eye

In [35]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Random

In [36]:
np.random.randn(8)

array([-0.55268303, -0.11558604, -0.4015578 ,  0.76907629, -0.9941359 ,
       -1.7080191 , -0.50151596,  0.99077771])

In [37]:
np.random.randn(4,4)

array([[ 0.34923737,  0.05149239,  1.29805211, -0.16662536],
       [-0.23080531, -0.37599852,  1.07768406,  0.43310411],
       [-0.84388281,  1.94047554,  0.72567038, -0.46867097],
       [ 0.97622074,  1.35815696,  1.04334943, -0.69068555]])

In [40]:
np.random.randint(1,10)

2

In [41]:
np.random.randint(1,50,5)

array([31, 22, 11, 13,  8])

In [42]:
numpyArray = np.arange(30)

In [43]:
numpyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])