In [36]:
import numpy as np

In [37]:
myArray = np.arange(0,15)

In [38]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
myArray[5]

5

In [40]:
myArray[3:5]

array([3, 4])

In [41]:
myArray[3:8] = -5

In [42]:
myArray

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [43]:
otherArray = np.arange(0,24)

In [44]:
otherArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [45]:
slicingArray = otherArray[4:9]

In [46]:
slicingArray[:] = 700

In [47]:
slicingArray

array([700, 700, 700, 700, 700])

In [48]:
myArray

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [49]:
slicingArray = 700

In [50]:
slicingArray

700

In [51]:
otherArray = np.arange(0,24)

In [52]:
otherArrayCopy = otherArray.copy()

In [53]:
otherArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [54]:
otherArrayCopy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [55]:
otherArrayCopySlicing = otherArrayCopy[3:6]

In [56]:
otherArrayCopySlicing[:] = 800

In [57]:
otherArrayCopySlicing

array([800, 800, 800])

In [58]:
otherArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
otherArrayCopy

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])