In [1]:
import numpy as np

## Matrix

In [2]:
myList = [[10,20,30],[40,50,60],[70,80,90]]

In [3]:
myMatrixArray = np.array(myList)

In [4]:
myMatrixArray

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [5]:
myMatrixArray[0]

array([10, 20, 30])

In [6]:
myMatrixArray[1][2]

60

In [7]:
myMatrixArray[1,2]

60

In [8]:
myMatrixArray[1:,2]

array([60, 90])

In [9]:
myMatrixArray[0:,2]

array([30, 60, 90])

In [10]:
myMatrixArray[0:,1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [18]:
newList = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]]

In [19]:
newMatrix = np.array(newList)

In [20]:
 newMatrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
newMatrix[[0,2,4]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25]])