In [1]:
import numpy as np

## Operations

In [4]:
newArray = np.random.randint(1,100,25)

In [5]:
newArray

array([31, 24, 29, 70, 81, 87, 78, 26, 34, 81, 92, 94, 11, 58, 47, 30,  9,
       88, 24, 40, 71, 14, 28, 14, 56])

In [8]:
resultArray = newArray > 24

In [9]:
resultArray

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
       False,  True,  True, False,  True, False,  True])

In [10]:
newArray

array([31, 24, 29, 70, 81, 87, 78, 26, 34, 81, 92, 94, 11, 58, 47, 30,  9,
       88, 24, 40, 71, 14, 28, 14, 56])

In [11]:
newArray[resultArray]

array([31, 29, 70, 81, 87, 78, 26, 34, 81, 92, 94, 58, 47, 30, 88, 40, 71,
       28, 56])

In [12]:
newArray[newArray > 24]

array([31, 29, 70, 81, 87, 78, 26, 34, 81, 92, 94, 58, 47, 30, 88, 40, 71,
       28, 56])

In [13]:
lastArray = np.arange(0,24)

In [14]:
lastArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [15]:
lastArray + lastArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [16]:
lastArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [17]:
lastArray * lastArray

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [18]:
lastArray - lastArray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [19]:
lastArray / lastArray

C:\Users\mert.guney\AppData\Local\Temp\ipykernel_14520\206178132.py:1: RuntimeWarning: invalid value encountered in divide
  lastArray / lastArray


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [20]:
np.sqrt(lastArray)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [21]:
np.max(lastArray)

23

In [22]:
np.min(lastArray)

0